trigger:
- master

resources:
  repositories:
  - repository: self

variables:
  tag: '$(Build.BuildId)'
# - name: imageRepository
#   value: 'presjkit/currency-exchange-devops'
# - name: containerRegistry
#   value: 'presjkit-docker-hub'
# - name: dockerfilePath
#   value: '**/Dockerfile'
# - name: tag
#   value: '$(Build.BuildId)'
# - name: vmImageName
#   value: 'ubuntu-latest'

stages:

# Stage 1
# Build Docker Image
# Publish the K8S Files

- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'presjkit-docker-hub'
        repository: 'presjkit/currency-exchange-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/configuration/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:  
   - deployment: Deploy
     displayName: Deploy
     pool:
      vmImage: ubuntu-latest
     environment:
      name: 'test'
     strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'manifests'
              itemPattern: |
                **/*.yml
                **/*.yaml
              targetPath: '$(Pipeline.Workspace)/manifests'
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'azure-kubernetes-service-connection'
              namespace: 'default'
              manifests: '$(Pipeline.Workspace)/manifests/deployment.yaml'
              containers: 'presjkit/currency-exchange-devops:$(tag)'
# Download the K8S Files
# Deploy to K8S Cluster with Docker Image